version: '2'
services:
  prevention-app:
    image: prevention
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://prevention-postgresql:5432/prevention
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8040:8040
  prevention-postgresql:
    extends:
      file: postgresql.yml
      service: prevention-postgresql
